name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4  # Tải mã nguồn từ GitHub về runner

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies and build project
      run: |
        npm install
        npm run build --if-present

    - name: Deploy
      run: |
        sudo cp -r client/build/* /var/www/html/
